# -*- coding: utf-8 -*-
"""ResNet50 implementaion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17CUrWgufmr1EIMH45qhpocb4tPXvC0uc
"""

#importing important dependancies
import pandas as ps
import numpy as np
import tensorflow as tf
import keras
from keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
import os
from os import listdir
from PIL import Image as PImage

#importing Resnet50 model from tensorflow Hub.
from keras.applications.resnet import ResNet50
from keras.applications.resnet import decode_predictions
from keras.applications.resnet import preprocess_input

img_width,img_hight  =224,224

model_pretrained = ResNet50(include_top=True,
                            weights='imagenet',
                            input_shape=(img_width,img_hight,3))

img_path = 'dog.jpg'
img = image.load_img(img_path,target_size=(img_width,img_hight))
img

img_data = image.img_to_array(img)

img = np.expand_dims(img_data,axis=0)

image_data = preprocess_input(img)

cnn_feature = model_pretrained.predict(image_data,verbose=0)
label = decode_predictions(cnn_feature)
label[0][0]

""" It predict 'pug' with 84.2% accuracy"""

def pred(path):
  img = image.load_img(path,target_size=(img_width,img_hight))
  img_array = image.img_to_array(img)
  imag = np.expand_dims(img_array,axis=0)
  image_data = preprocess_input(imag)
  cnn_feature = model_pretrained.predict(image_data)
  label = decode_predictions(cnn_feature)
  return label

print(pred('/content/cat_test.jpg'))

